winzou_state_machine:
    sylius_order_payment:
        callbacks:
            before:
                sylius_complete_payment:
                    on: ["pay", "refund"]
                    do: ["@setono.payum_gateway.state_resolver", "resolve"]
                    args: ["object"]
