setono_sylius_quickpay_global:
    resource: "@SetonoSyliusQuickpayPlugin/Resources/config/routes/global.yaml"

setono_sylius_quickpay_admin:
    resource: "@SetonoSyliusQuickpayPlugin/Resources/config/routes/admin.yaml"
    prefix: '/%sylius_admin.path_name%'
