services:
    setono.payum_gateway.state_resolver:
        class: Setono\SyliusQuickpayPlugin\StateMachine\Resolver
        arguments: ['@sm.factory']
        public: true

    setono.payum_gateway_form.quickpay_gateway_configuration:
        class: Setono\SyliusQuickpayPlugin\Form\Type\QuickPayGatewayConfigurationType
        tags:
            - { name: 'sylius.gateway_configuration_type', type: 'quickpay', label: 'setono.payum_gateway_factory.quickpay' }

    setono.payum_gateway_factory.quickpay:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Setono\Payum\QuickPay\QuickPayGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: quickpay }
