winzou_state_machine:
    sylius_payment:
        callbacks:
            before:
                setono_quickpay_resolve_state:
                    on: ["complete", "refund", "cancel"]
                    do: ["@setono_sylius_quickpay.state_machine.payment_processor", "__invoke"]
                    args: ["object", "event"]
