sylius_fixtures:
    suites:
        default:
            fixtures:

                setono_quickpay_geographical:
                    name: geographical
                    options:
                        countries:
                            - 'DK'
                            - 'NL'
                        zones:
                            EU:
                                name: "EU"
                                scope: "all"
                                countries:
                                    - 'DK'
                                    - 'NL'
                setono_quickpay_currency:
                    name: currency
                    options:
                        currencies: 
                            - "DKK"

                setono_quickpay_channel:
                    name: channel
                    options:
                        custom:
                            eu_web_store:
                                name: "EU Web Store"
                                code: "EU_WEB"
                                locales:
                                    - "%locale%"
                                currencies:
                                    - "EUR"
                                enabled: true
                                hostname: "localhost"
                            dk_web_store:
                                name: "DK Web Store"
                                code: 'DK_WEB'
                                locales:
                                    - "%locale%"
                                currencies:
                                    - "DKK"
                                enabled: true
                                hostname: "localhost"
                            nl_web_store:
                                name: "NL Web Store"
                                code: 'NL_WEB'
                                locales:
                                    - "%locale%"
                                currencies:
                                    - "EUR"
                                enabled: true
                                hostname: "localhost"

                setono_quickpay_klarna_test_shop_user_dk:
                    name: setono_quickpay_klarna_test_shop_user
                    options:
                        amount: 10
                        country: DK

                setono_quickpay_klarna_test_shop_user_nl:
                    name: setono_quickpay_klarna_test_shop_user
                    options:
                        amount: 10
                        country: NL

                setono_quickpay_payment_method:
                    name: payment_method
                    options:
                        custom:
                            quickpay_credit_card:
                                code: 'quickpay_credit_card'
                                name: 'Creditcard via QuickPay'
                                instructions: 'Pay via QuickPay with credit card'
                                gatewayName: 'quickpay_credit_card'
                                gatewayFactory: quickpay
                                gatewayConfig:
                                    apikey: '%env(resolve:QUICKPAY_API_KEY)%'
                                    privatekey: '%env(resolve:QUICKPAY_PRIVATE_KEY)%'
                                    merchant: '%env(resolve:QUICKPAY_MERCHANT_ID)%'
                                    agreement: '%env(resolve:QUICKPAY_AGREEMENT_ID)%'
                                    order_prefix: '%env(resolve:QUICKPAY_ORDER_PREFIX)%'

                                    # https://learn.quickpay.net/tech-talk/appendixes/payment-methods/#payment-methods
                                    payment_methods: 'creditcard'

                                    # https://learn.quickpay.net/tech-talk/guides/payments/#introduction-to-payments
                                    # If you are selling a digital products, you can include "auto_capture":"true" 
                                    # in the payment link request, to capture the payment automatically after the authorize.
                                    auto_capture: 0

                                    use_authorize: true
                                channels:
                                    - 'FASHION_WEB'
                                    - 'EU_WEB'
                                    - 'DK_WEB'
                                    - 'NL_WEB'
                                enabled: true
                            quickpay_klarna:
                                code: 'quickpay_klarna'
                                name: 'Klarna via QuickPay'
                                instructions: 'Pay via QuickPay with Klarna account'
                                gatewayName: 'quickpay_klarna'
                                gatewayFactory: quickpay
                                gatewayConfig:
                                    apikey: '%env(resolve:QUICKPAY_API_KEY)%'
                                    privatekey: '%env(resolve:QUICKPAY_PRIVATE_KEY)%'
                                    merchant: '%env(resolve:QUICKPAY_MERCHANT_ID)%'
                                    agreement: '%env(resolve:QUICKPAY_AGREEMENT_ID)%'
                                    order_prefix: '%env(resolve:QUICKPAY_ORDER_PREFIX)%'

                                    # https://learn.quickpay.net/tech-talk/appendixes/payment-methods/#payment-methods
                                    payment_methods: 'klarna'

                                    # https://learn.quickpay.net/tech-talk/guides/payments/#introduction-to-payments
                                    # If you are selling a digital products, you can include "auto_capture":"true" 
                                    # in the payment link request, to capture the payment automatically after the authorize.
                                    auto_capture: 0

                                    use_authorize: true
                                channels:
                                    - 'DK_WEB'
                                    - 'NL_WEB'
                                enabled: true

                setono_quickpay_shipping_method:
                    name: shipping_methody
                    options:
                        custom:
                            eu_courier:
                                code: 'eu_courier'
                                name: 'EU courier'
                                zone: 'EU'
                                enabled: true
                                channels:
                                    - 'EU_WEB'
                                    - 'DK_WEB'
                                    - 'NL_WEB'

                setono_quickpay_cap_product_nl:
                    name: product
                    options:
                        custom:
                            -   name: 'Winter cap'
                                tax_category: 'other'
                                channels:
                                    - 'NL_WEB'
                                main_taxon: 'caps_with_pompons'
                                taxons:
                                    - 'caps'
                                    - 'caps_with_pompons'
                                images:
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/caps/cap_01.jpg', type: 'main' }
